set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ARM_GCC_ROOT)
if(NOT ARM_GCC_ROOT)
  message(FATAL_ERROR "Pass -DARM_GCC_ROOT=<GNU Arm toolchain directory>")
endif()
file(TO_CMAKE_PATH "${ARM_GCC_ROOT}" ARM_GCC_ROOT)
set(CMAKE_C_COMPILER "${ARM_GCC_ROOT}/bin/arm-none-eabi-gcc.exe")
set(CMAKE_OBJCOPY "${ARM_GCC_ROOT}/bin/arm-none-eabi-objcopy.exe")
set(CMAKE_SIZE "${ARM_GCC_ROOT}/bin/arm-none-eabi-size.exe")
set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
